include ( TestBigEndian )
include ( CheckCCompilerFlag )

test_big_endian ( BIGENDIAN )
if ( BIGENDIAN )
	set ( BYTEORDER 4321 )
  set ( WORDS_BIGENDIAN 1 )
else ()
  set ( BYTEORDER 1234 )
endif ()

include ( CheckFunctionExists )
check_function_exists ( bcopy HAVE_BCOPY )
check_function_exists ( pagesize HAVE_PAGESIZE )
check_function_exists ( memmove HAVE_MEMMOVE )
check_function_exists ( mmap HAVE_MMAP )

include ( CheckIncludeFiles )
check_include_files ( dlfcn.h HAVE_DLFCN_H )
check_include_files ( inttypes.h HAVE_INTTYPES_H )
check_include_files ( memory.h HAVE_MEMORY_H )
check_include_files ( stdint.h HAVE_STDINT_H )
check_include_files ( stdlib.h HAVE_STDLIB_H )
check_include_files ( strings.h HAVE_STRINGS_H )
check_include_files ( string.h HAVE_STRING_H )
check_include_files ( sys/stat.h HAVE_SYS_STAT_H )
check_include_files ( unistd.h HAVE_UNISTD_H )
check_include_files ( sys/types.h HAVE_SYS_TYPES_H )

if ( NOT HAVE_SYS_TYPES_H )
  set ( OFF_T long )
  set ( SIZE_T ungigned )
endif ()

check_c_compiler_flag(-fno-keep-inline-dllexport HAVE_FNO_KEEP_INLINE_DLLEXPORT) # gcc >= 4.6.1
