
set( wx_use_true

wxUSE_GUI
wxUSE_ON_FATAL_EXCEPTION
wxUSE_STACKWALKER
wxUSE_DEBUGREPORT
wxUSE_UNICODE
wxUSE_WCHAR_T
wxUSE_EXCEPTIONS

wxUSE_LOG
wxUSE_LOGWINDOW
wxUSE_LOGGUI
wxUSE_LOG_DIALOG
wxUSE_CMDLINE_PARSER
wxUSE_THREADS
wxUSE_STREAMS
wxUSE_PRINTF_POS_PARAMS
wxUSE_COMPILER_TLS
wxUSE_STD_IOSTREAM
wxUSE_STD_STRING

wxUSE_LONGLONG
wxUSE_BASE64
wxUSE_CONSOLE_EVENTLOOP
wxUSE_FILE
wxUSE_FFILE
wxUSE_FSVOLUME
wxUSE_STDPATHS
wxUSE_TEXTBUFFER
wxUSE_TEXTFILE
wxUSE_INTL
wxUSE_XLOCALE
wxUSE_DATETIME
wxUSE_TIMER
wxUSE_STOPWATCH
wxUSE_FSWATCHER
wxUSE_CONFIG
wxUSE_CONFIG_NATIVE

wxUSE_DYNLIB_CLASS
wxUSE_DYNAMIC_LOADER
wxUSE_SOCKETS

wxUSE_FILESYSTEM
wxUSE_FS_ZIP
wxUSE_FS_ARCHIVE
wxUSE_FS_INET
wxUSE_ARCHIVE_STREAMS
wxUSE_ZIPSTREAM
wxUSE_TARSTREAM
wxUSE_ZLIB
wxUSE_APPLE_IEEE

wxUSE_FONTENUM
wxUSE_FONTMAP
wxUSE_MIMETYPE
wxUSE_PROTOCOL
wxUSE_PROTOCOL_FILE
wxUSE_PROTOCOL_FTP
wxUSE_PROTOCOL_HTTP
wxUSE_URL

wxUSE_VARIANT
wxUSE_ANY
wxUSE_REGEX
wxUSE_SYSTEM_OPTIONS
wxUSE_SOUND
wxUSE_MEDIACTRL
wxUSE_XRC
wxUSE_XML
wxUSE_AUI
wxUSE_RIBBON
wxUSE_PROPGRID
wxUSE_STC



wxUSE_GRAPHICS_CONTEXT

wxUSE_CONTROLS
wxUSE_MARKUP
wxUSE_POPUPWIN
wxUSE_TIPWINDOW
wxUSE_ANIMATIONCTRL
wxUSE_BANNERWINDOW
wxUSE_BUTTON
wxUSE_BMPBUTTON
wxUSE_CALENDARCTRL
wxUSE_CHECKBOX
wxUSE_CHECKLISTBOX
wxUSE_CHOICE
wxUSE_COLLPANE
#wxUSE_COLOURPICKERCTRL	# docasne
wxUSE_COMBOBOX
wxUSE_COMMANDLINKBUTTON
wxUSE_DATAVIEWCTRL
wxUSE_DATEPICKCTRL
wxUSE_DIRPICKERCTRL
wxUSE_EDITABLELISTBOX
wxUSE_FILECTRL
wxUSE_FILEPICKERCTRL
wxUSE_FONTPICKERCTRL
wxUSE_GAUGE
wxUSE_HEADERCTRL
wxUSE_HYPERLINKCTRL
wxUSE_LISTBOX
wxUSE_LISTCTRL
wxUSE_RADIOBOX
wxUSE_RADIOBTN
wxUSE_RICHMSGDLG
wxUSE_SCROLLBAR
wxUSE_SEARCHCTRL
wxUSE_SLIDER
wxUSE_SPINBTN
wxUSE_SPINCTRL
wxUSE_STATBOX
wxUSE_STATLINE
wxUSE_STATTEXT
wxUSE_STATBMP
wxUSE_TEXTCTRL
wxUSE_TIMEPICKCTRL
wxUSE_TOGGLEBTN
wxUSE_TREECTRL
wxUSE_TREELISTCTRL
wxUSE_STATUSBAR
wxUSE_NATIVE_STATUSBAR
wxUSE_TOOLBAR
wxUSE_TOOLBAR_NATIVE
wxUSE_NOTEBOOK
wxUSE_LISTBOOK
wxUSE_CHOICEBOOK
wxUSE_TREEBOOK
wxUSE_TOOLBOOK
wxUSE_TASKBARICON
wxUSE_GRID
wxUSE_MINIFRAME
wxUSE_COMBOCTRL
wxUSE_ODCOMBOBOX
wxUSE_BITMAPCOMBOBOX
wxUSE_REARRANGECTRL
wxUSE_ACCEL
wxUSE_ARTPROVIDER_STD

wxUSE_CARET
wxUSE_DISPLAY
wxUSE_GEOMETRY
wxUSE_IMAGLIST
wxUSE_INFOBAR
wxUSE_MENUS
wxUSE_NOTIFICATION_MESSAGE
wxUSE_PREFERENCES_EDITOR
wxUSE_RICHTOOLTIP
wxUSE_SASH
wxUSE_SPLITTER
wxUSE_TOOLTIPS
wxUSE_VALIDATORS
#wxUSE_AUTOID_MANAGEMENT
#wxUSE_COMMON_DIALOGS
wxUSE_BUSYINFO
wxUSE_CHOICEDLG
wxUSE_COLOURDLG
wxUSE_DIRDLG
wxUSE_FILEDLG
wxUSE_FINDREPLDLG
wxUSE_FONTDLG
wxUSE_MSGDLG
wxUSE_PROGRESSDLG
wxUSE_STARTUP_TIPS
wxUSE_TEXTDLG
wxUSE_NUMBERDLG
wxUSE_SPLASH
wxUSE_WIZARDDLG
wxUSE_ABOUTDLG
wxUSE_FILE_HISTORY


wxUSE_MDI
wxUSE_DOC_VIEW_ARCHITECTURE
wxUSE_MDI_ARCHITECTURE
wxUSE_PRINTING_ARCHITECTURE
wxUSE_HTML
wxUSE_GLCANVAS
wxUSE_RICHTEXT
wxUSE_CLIPBOARD
wxUSE_DATAOBJ
wxUSE_DRAG_AND_DROP

wxUSE_SNGLINST_CHECKER
wxUSE_DRAGIMAGE
wxUSE_IPC
wxUSE_HELP
#wxUSE_MS_HTML_HELP
wxUSE_WXHTML_HELP
wxUSE_CONSTRAINTS
wxUSE_SPLINES
wxUSE_MOUSEWHEEL
wxUSE_UIACTIONSIMULATOR
wxUSE_POSTSCRIPT
wxUSE_AFM_FOR_POSTSCRIPT
wxUSE_SVG
wxUSE_DC_TRANSFORM_MATRIX
wxUSE_IMAGE
wxUSE_LIBPNG
wxUSE_LIBJPEG
wxUSE_LIBTIFF
wxUSE_TGA
wxUSE_GIF
wxUSE_PNM
wxUSE_PCX
wxUSE_IFF
wxUSE_XPM
wxUSE_ICO_CUR
wxUSE_PALETTE

wxUSE_SELECT_DISPATCHER


wxUSE_RICHEDIT
wxUSE_RICHEDIT2

wxUSE_TASKBARICON_BALLOONS

wxUSE_OPENGL



)

foreach( wx_use ${wx_use_true} )
	set( ${wx_use} 1 )
endforeach()


###############################################################################################

if(UNIX AND NOT APPLE)
	set( wxUSE_UNIX 1)

	set( wxUSE_DIALUP_MANAGER 1)
	set( wxUSE_JOYSTICK 1 )
	set( wxUSE_WEBVIEW 0 )
	set( wxUSE_WEBVIEW_WEBKIT 0 )
	set( wxUSE_CAIRO 1 )
	set( wxUSE_ARTPROVIDER_TANGO 0 )
	set( wxUSE_HOTKEY 0 )
	set( wxUSE_METAFILE 0 )
	set( wxUSE_EPOLL_DISPATCHER 1 )

	#set( wxUSE_GSTREAMER 1 ) # docasne vypnute: potrebuje libxml

	set( wxUSE_DETECT_SM 1 )
	set( wxUSE_GTKPRINT 1 )

	set( wxUSE_STD_DEFAULT 1)

	set( wxHAS_INOTIFY 1)

endif()

if(APPLE)
	set( wxUSE_UNIX 1 )
	set( wxUSE_DIALUP_MANAGER 0)
	set( wxUSE_JOYSTICK 0 )
	set( wxUSE_WEBVIEW 1 )
	set( wxUSE_WEBVIEW_WEBKIT 1 )
	set( wxUSE_CAIRO 0 )
	set( wxUSE_ARTPROVIDER_TANGO 1 )
	set( wxUSE_HOTKEY 1 )
	set( wxUSE_METAFILE 1 )
	set( wxUSE_EPOLL_DISPATCHER 0 )
	set( wxUSE_GSTREAMER 0 )
	set( wxUSE_WEBKIT 1 )
	set( wxUSE_DETECT_SM 0 )
	set( wxUSE_GTKPRINT 0 )

	set( wxUSE_STD_DEFAULT 1)

	set( wxUSE_WEBKIT 1 )

	set( wxHAS_KQUEUE 1)
endif()



if(WIN32)
#wxUSE_WEBVIEW_IE
#wxUSE_ENH_METAFILE
#wxUSE_WIN_METAFILES_ALWAYS
#wxUSE_MFC
#wxUSE_OLE
#wxUSE_OLE_AUTOMATION
#wxUSE_ACTIVEX
endif()

###############################################################################################

set( wx_use_false
wxUSE_NANOX
wxUSE_DEBUG_CONTEXT
wxUSE_MEMORY_TRACING
wxUSE_GLOBAL_MEMORY_OPERATORS
wxUSE_DEBUG_NEW_ALWAYS
wxUSE_STL

wxUSE_STD_CONTAINERS
wxUSE_IOSTREAMH
wxUSE_IPV6
wxUSE_URL_NATIVE
wxUSE_ACCESSIBILITY

wxUSE_EXTENDED_RTTI



#wxUSE_ALL_THEMES
#wxUSE_CRASHREPORT
#wxUSE_DATEPICKCTRL_GENERIC
#wxUSE_DC_CACHEING
#wxUSE_INICONF
#wxUSE_INKEDIT
#wxUSE_LIBGNOMEVFS
#wxUSE_LIBHILDON
#wxUSE_LIBHILDON2
#wxUSE_LIBMSPACK
#wxUSE_LIBNOTIFY
#wxUSE_LIBNOTIFY__7
#wxUSE_LIBSDL
#wxUSE_OBJC_UNIQUIFYING
#wxUSE_OWNER_DRAWN
#wxUSE_PLUGINS
#wxUSE_POSTSCRIPT_ARCHITECTURE_IN_MSW
#wxUSE_REGKEY
#wxUSE_THEME_GTK
#wxUSE_THEME_METAL
#wxUSE_THEME_MONO
#wxUSE_THEME_WIN32
#wxUSE_TIMEPICKCTRL_GENERIC
#wxUSE_UNICODE_MSLU
#wxUSE_UNICODE_UTF8
#wxUSE_UTF8_LOCALE_ONLY
#wxUSE_UXTHEME
#wxUSE_WXDIB
)

foreach( wx_use ${wx_use_false} )
	set( ${wx_use} 0 )
endforeach()

###############################################################################################
